- name: Just force systemd to reread configs 
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable service etcd and ensure it is not masked
  ansible.builtin.systemd:
    name: etcd
    enabled: true
    masked: no

- name: Make sure a service etcd unit is running
  ansible.builtin.systemd:
    state: started
    name: etcd
