vms_name = [ "bastion" ]
vms_domain = [ "k8s.xprd.local", "k8s.xprd.local" ]
vms_ip_type = [ "dhcp", "dhcp" ]
vms_memoryMB = [ 2048, 2048 ]
vms_cpu = [ 1 , 1 ]
vms_pool = [ "kvmpool01" ]
vms_disk = [ 20 ]
ansible_user="xavier"
image_path="/home/xavier/Downloads"
image_name="jammy-server-cloudimg-amd64.img"
