---
# tasks file for guac-guacamole
- name: install pre-requisite packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
     - build-essential 
     - libcairo2-dev 
     - libjpeg-turbo8-dev
     - libjpeg-turbo8
     - libpng-dev 
     - libtool-bin 
     - uuid-dev 
     - libossp-uuid-dev 
     - libavcodec-dev 
     - libavformat-dev 
     - libavutil-dev 
     - libswscale-dev 
     - freerdp2-dev 
     - libpango1.0-dev 
     - libssh2-1-dev 
     - libvncserver-dev 
     - libtelnet-dev 
     - libwebsockets-dev 
     - libssl-dev 
     - libvorbis-dev 
     - libwebp-dev 
     - libpulse-dev 
     - sudo 
     - vim
     - ffmpeg

- name: download guacamole source
  get_url:
     url: https://downloads.apache.org/guacamole/{{ guac_version }}/source/guacamole-server-{{ guac_version }}.tar.gz
     dest: /tmp

- name: uncompress guacamole source
  unarchive:
     src: /tmp/guacamole-server-{{ guac_version }}.tar.gz
     dest: /tmp
     remote_src: true

- name: compile guacamole
  shell: "cd /tmp/guacamole-server-{{ guac_version }} ; ./configure --with-systemd-dir=/etc/systemd/system/ ; make ; make install ; ldconfig"

- name: recrete hosts file
  copy:
     dest: /etc/hosts
     content: |
       "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ hostvars[item]['ansible_hostname']}}"
       "127.0.0.1 localhost"
  with_items: "{{groups['all']}}"

- name: restart services
  systemd_service:
     state: restarted
     daemon_reload: true
     name: guacd
